{
  "services": [
    {
      "name": "sah-music-bot",
      "env": "node",
      "region": "frankfurt",
      "buildCommand": "cd bot && npm install",
      "startCommand": "cd bot && node index.js",
      "envVars": [
        {
          "key": "BOT_TOKEN",
          "value": "8617424300:AAGe4mJ7yHWCTmgBzb1DQ7cEw8UAYw0FFqQ"
        },
        {
          "key": "WEBAPP_URL",
          "value": "https://sah-music.vercel.app"
        },
        {
          "key": "SUPABASE_URL",
          "value": "https://fosectnadqffvrnepdbo.supabase.co"
        },
        {
          "key": "SUPABASE_KEY",
          "value": "sb_publishable_j6JbOMEQjHUILKKpmExnuw_LSCGKWvv"
        }
      ],
      "plan": "free"
    }
  ]
}
